---
output: github_document
---





# 1. Motivation and purpose
  When looking for houses, one important factor that people will consider is the safety of the neighborhood. Searching that information district by district could be time consuming and exhausting. It is even harder to compare specific crime statistics across districts like the crime rate at a certain time point which some people might care about if their work ends really late. It would be useful if people can just look up crime related information across district on one mobile application. Our app aims to help people make decisions when considering potential dwellings via visually explore a dataset of crime statistics in San Francisco, United State. The app provides an overview of the crime rate across districts and allows users to focus on more specific information through filtering via geological location,crime rate, crime type or time of the crime.


#3. Research questions and usage scenarios 
  Imagine Anny, she’s a frequent traveler and knows that no matter which city or country she’s going to visit – safety comes first. She decided to plan a trip to San Francisco, but she’d never been there and doesn’t know much about the neighborhoods. She wants to make sure that her trip will be as safe as possible and receive only good memories from it. As a part of her planning process, she wants to [get more insight] about the current crime rate situation in San Francisco. Anny wants to [explore] the data set and [identify] the most appealing neighborhood for her short stay. Anny also owns and travels in her own car, so her biggest concern is vehicle theft. Because who wants to find themselves in an unfamiliar city without their primary method of transportation, right? Therefore, she wants to be able to only [choose parameters of interest] during her planning process. When Anny logs into the Victorious Secret dashboard she will see an overview of all the available variables (types of criminal offenses) in her dataset, according to the neighborhood where the crime was committed. She can filter out variables that are not relevant to her situation and find the most appropriate neighborhood for her stay.
  Let’s also look at David. Recently moved to San Francisco for work he is now in the middle of an apartment hunt. He approximately knows in what neighborhoods he can afford accommodation, but how to choose between them? He’s logging into the Victorious Secret dashboard, now he’s able to choose all the neighborhoods he’s interested in and see which one is the safest overall, or at least has the least vandalism or theft rating. In an additional graph in the dashboard, where you can see a per hour rate occurrences, he noticed that the peak hour for theft is around the 18-hour mark. David started to think that this must be a concern for his safety, as he’s usually just getting back home from work at that time and decided to invest more in house alarms.
  And finally, Angela she’s an investigative journalist, who wants to dive deep into criminal records of San Francisco and find answers for her article. The most important questions that she raises are: what was the most notorious crime for the deduced hours and how do these 4 crimes vary across different districts and what was the district with highest incidence reports for each of the top 4 crimes? She logs into the dashboard and goes through hours and locations. Angela sees that Southern district is the most notorious for assault, larceny/theft, and vandalism crimes, with more density towards the border between Mission and Northern districts. And the number of top four criminal offenses reported rises from 5 am onwards and peak at 6 pm. Moreover, this count drops after 6 pm and is at its lowest at 5 am. That made her think that she needs to conduct a follow-on study about the working hours of people in those districts.
